version: '3.8'

services:
  messagio:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty


  db:
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432


#  kafka:
#    image: apache/kafka:latest
#    container_name: kafka
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#    ports:
#      - 9092:9092
#    depends_on:
#      - zookeeper
#    networks:
#      - messagio-net
#
#  zookeeper:
#    image: zookeeper:latest
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#    ports:
#      - 2181:2181
#    networks:
#      - messagio-net
#
#networks:
#  messagio-net:
#    driver: bridge